### ISSUE TITLE
Skip local path dependencies in pyproject.toml ?

### ISSUE THREAD

**Issue by njlr** [jvolkman/rules_pycross#134]
This cannot currently be parsed by `lock_repo_model_poetry`:

```toml
[tool.poetry]
name = "foobar"
version = "0.0.1"
description = "Foo Bar"
authors = ["Engineering <engineering@acme.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
abc = { path = "../abc", develop = false }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Perhaps `path` dependencies should be skipped, rather than throw an error?
The usual Bazel approach is to include these in `deps`. 

The current work-around is to maintain two project files: one for `rules_pycross` and one for regular Python tooling. 

This could be put behind a flag - `skip_path_dependencies = True`?
